# -*- coding: utf-8 -*-
"""Weight Exporter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEDMqiB8iq7yw3tFoMZnRBNhm4qfE1j5
"""

import torch
import torch.nn as nn
import os

# 1. Match your exact C++ architecture
layers = [
    nn.Linear(1024, 512),
    nn.Linear(512, 128),
    nn.Linear(128, 10)
]

FILENAME = "multi_model_weights.bin"
print(f"Exporting PyTorch weights to {FILENAME}...")

# 2. Dump raw memory to disk
with open(FILENAME, "wb") as f:
    for i, layer in enumerate(layers):
        # Transpose W for our Cache-Tiled engine (X * W)
        W = layer.weight.detach().numpy().T
        B = layer.bias.detach().numpy()

        f.write(W.tobytes())
        f.write(B.tobytes())

file_size = os.path.getsize(FILENAME) / (1024 * 1024)
print(f"[SUCCESS] Wrote {file_size:.2f} MB of raw Neural Network weights.")